version: "3"
services:
  db:
    image: postgres:alpine
    container_name: itcrowd_database
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - apps

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: itcrowd_server:dev
    container_name: itcrowd_server
    env_file: .env
    volumes:
      - ./server:/var/www/server
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
    networks:
      - apps

  client:
    stdin_open: true
    container_name: itcrowd_client
    build:
      context: .
      dockerfile: Dockerfile.client
    image: itcrowd_client:dev
    env_file: .env
    volumes:
      - ./client:/var/www/client
      - /var/www/client/node_modules
    ports:
      - 80:80
      - 8080:8080
    links:
      - server
    depends_on:
      - server
    networks:
      - apps

volumes:
  postgres:
networks:
  apps:
    driver: bridge
