FROM node:12-alpine3.12

RUN apk update && apk upgrade && apk add --update --no-cache tzdata zsh git
RUN CI=true

WORKDIR /var/www/client
ENV PATH=/var/www/client/node_modules/.bin:$PATH

COPY ./client/package.json ./
COPY . ./

EXPOSE 80